### ISSUE TITLE
Needs SharePoint PUT, PATCH, DELETE examples

### ISSUE THREAD

**Issue by nigel-dewar** [OfficeDev/O365-Node-Express-Ejs-Sample-App#2]
Hi, this isn't really an issue, but thought it would be a nice to have. Since I'm going through this exercise myself at the minute, and now realize, an example would be really nice.

If anyone gets time, updating this project with PUT, PATCH, DELETE examples for SharePoint lists would be great. And again, save students alot of time.

cheers. :-)

**Comment by kdeding** [comment]
Nigel, 

I've uploaded an update of the sample to include the features you mentioned. It turned out that the SharePoint doesn't take PUT, PATCH and DELETE requests. Instead, one must POST with a X-HTTP-METHOD header set to MERGE or DELETE. Check the sample for details. 

Cheers,
Kurt

**Comment by nigel-dewar** [comment]
Thanks very much Kurt.

 

Yes I found these out the hard way too. Its great that you have updated this. Your project will be super valuable for folks now because it contains the 2 most important elements, ‘in my opinion anyway’ CRUD to SP, and Mail. 

 

Sahat, ( creator of satellizer ) https://github.com/sahat/satellizer is working on getting Azure AD auth going in this package so that is pretty cool. O365,Azure should really start to take off in the node community hard core ( if not already ). I’ve gotta send him over some notes on azure ad auth, and I’ll let him know about your project if he doesn’t know about it already.

 

I’m getting MS SQL Server going with my node package, using Tedious http://pekim.github.io/tedious/  which using the TDS ‘Tabular Data Stream’ ( for anyone else reading this github post ), to connect to SQL server 2000 – 2012 and possibly 2014.  It works pretty well. The advantage of Tedious, is that you don’t have to install all the windows specific stuff to connect to SQL server from node. So you can use a linux, mac OS, to connect, and that’s cool.

 

I’m putting together a 2 Tier – Node/Express(backend) + Angular(frontend with gulp) project that leverages a bunch of your code ‘hope you don’t mind’, that hopefully will serve as a boilerplate/demo start-up project for guys wanting to use node in enterprise. So its setup where you have Azure AD, Full CRUD to all of the O365 endpoints (especially SharePoint), and full example of using SQL Server which I feel is a must have for an enterprise boilerplate I’d say. The project will still use a Mongo DB for its main database, but SQL server will still be included in setup.

 

I’ll post it up when its ready and you can check it out for a laugh. =) and I mean that, it will be amateur code, but hopefully it will help a few folks out, as much as your project already is.

 

Thanks again Kurt. Love your work!

**Comment by kdeding** [comment]
Nigel,

Thanks for your feedback and sharing your project-in-progress. It’s great to hear about your project. It sounds very interesting. I look forward to checking it out when you put it up. I myself tinkled with Tedious, just a bit, but haven’t gone much further than making a simple query. I’d be interested in learning more about Tedious from your project.  Keep me posted.

Yes, please share my code as you see fit. It’s meant for sharing and we’re here to help each other to succeed. ☺

Cheers,
Kurt
