### ISSUE TITLE
office-js' is not in the npm registry

### ISSUE THREAD

**Issue by fredrikj** [OfficeDev/O365-Node-Express-Ejs-Sample-App#3]
It does not seem to be possible to run this, since doing "npm install" results in:

```
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/office-js
npm ERR! 404
npm ERR! 404 'office-js' is not in the npm registry.
```

**Comment by MIchaelMainer** [comment]
I removed the office-js dependency from packages.json. It works fine now.

**Comment by MIchaelMainer** [comment]
@fredrikj I almost forgot, thank you for opening the issue.
