### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by julianfrank** [OfficeDev/O365-Node-Express-Ejs-Sample-App#5]
I tried by creating the client id and secret in the new portal...https://apps.dev.microsoft.com

This sample does not work....Error is as follows:
https://localhost:3000/getAToken?error=unauthorized_client&error_description=AADSTS70001%3a+Application+%27cbb12a4b-fc50-4c72-ba1f-e5c30615761e%27+is+not+supported+for+this+API+version.%0d%0aTrace+ID%3a+c43e9669-b254-48bd-b8c7-912ac736f5f1%0d%0aCorrelation+ID%3a+5adc6722-4767-4895-9371-f79fe131cdde%0d%0aTimestamp%3a+2015-12-10+10%3a29%3a42Z

**Comment by julianfrank** [comment]
Just tried again with the client id and secret generated from old portal (manage.windowsazure.com)...It Works ...Gues  you need to update to handle the client id/secret from new portal as well...

**Comment by MIchaelMainer** [comment]
@julianfrank Thank you for informing us of the error you found.
